---
title: "UntitledUnderstanding Vulnerability: Toronto Police Service's Annual Statistical Report on Crimes Against the Person (2014-2022)"
author: "Jagpreet Singh"
format: pdf
editor: visual
---

```{r}
knitr::opts_chunk$set(echo = FALSE, results ="hide", message = FALSE, warning = FALSE)
```
```{r}
#| lable: Table 1

library("tidyverse")

# Read data
crime_data <- read_csv("output/data/edited_data.csv",show_col_types = FALSE) 
column_specifications <- spec(crime_data)

# Calculate total number of crimes reported per year
total_counts <- aggregate(COUNT_ ~ REPORT_YEAR, data = crime_data, sum)

# Create a data frame for the table
crime_table <- data.frame(Year = total_counts$REPORT_YEAR, Total_Number_of_Crimes = total_counts$COUNT_)

# Print the table
print(crime_table)
```

```{r}


#| label - Fig-1

library("tidyverse")

# Read data
crime_data <- read_csv("output/data/edited_data.csv",show_col_types = FALSE) 
column_specifications <- spec(crime_data)
# Calculate total number of crimes reported per year
total_counts <- aggregate(COUNT_ ~ REPORT_YEAR, data = crime_data, sum)  
# Create a bar graph using ggplot2 
ggplot(total_counts, aes(x = as.factor(REPORT_YEAR), y = COUNT_)) +   
  geom_bar(stat = "identity", fill = "blue", alpha = 0.7) + 
   geom_line(aes(group = 1), stat = "smooth", method = "lm", se = FALSE, color = "red", linetype = "solid") +  # Add trendline
  labs(title = "Total count of crimes against the person per year (2014-2022)",      
       x = "Year",        
       y = "Total Number of Crimes") +  
  scale_y_continuous(breaks = seq(0, max(total_counts$COUNT_), by = 2000)) + # Set y-axis breaks
  theme_minimal()


```


```{r}

#| label: fig-2

# Read data
crime_data <- read_csv("output/data/edited_data.csv", show_col_types = FALSE) 
column_specifications <- spec(crime_data)

# Aggregate total counts by REPORT_YEAR and SUBTYPE
subtype_counts <- aggregate(COUNT_ ~ REPORT_YEAR + SUBTYPE, data = crime_data, sum)

# Create a bar graph using ggplot2 with subtype on the bars
ggplot(subtype_counts, aes(x = as.factor(REPORT_YEAR), y = COUNT_, fill = SUBTYPE)) +
  geom_bar(stat = "identity", position = "dodge", alpha = 0.7) +
  labs(title = "Total count of crimes against the person per year by type of crime (2014-2022)",
       x = "Year",
       y = "Total Number of Crimes") +
  scale_y_continuous(breaks = seq(0, max(subtype_counts$COUNT_), by = 2000)) +
  theme_minimal()
```


```{r}

#| label: fig-3

# Read data
crime_data <- read_csv("output/data/edited_data.csv", show_col_types = FALSE) 
column_specifications <- spec(crime_data)

# Aggregate total counts by REPORT_YEAR and SEX 
sex_counts <- aggregate(COUNT_ ~ REPORT_YEAR + SEX, data = crime_data, sum)

# Create a scatter plot using ggplot2 with sex on the x-axis
ggplot(sex_counts, aes(x = as.factor(REPORT_YEAR), y = COUNT_, color = SEX)) +
  geom_point(size = 3, alpha = 0.7) +
  labs(title = "Total count of crimes against the person of each sex per year",
       x = "Year",
       y = "Total Number of Crimes") +
  scale_y_continuous(breaks = seq(0, max(sex_counts$COUNT_), by = 2000)) +
  scale_color_manual(values = c("F" = "blue", "M" = "red", "U" = "brown"),
                     labels = c("F" = "Female", "M" = "Male", "U" = "Unknown")) +  # Specify colors and labels
  theme_minimal()

```
```{r}

#| label: fig-4

# Read data
crime_data <- read_csv("output/data/edited_data.csv", show_col_types = FALSE) 
column_specifications <- spec(crime_data)

# Aggregate total counts by REPORT_YEAR and AGE_GROUP
age_counts <- aggregate(COUNT_ ~ REPORT_YEAR + AGE_GROUP, data = crime_data, sum)

# Create a line graph using ggplot2 with age_group on the x-axis
ggplot(age_counts, aes(x = as.factor(REPORT_YEAR), y = COUNT_, color = AGE_GROUP, group = AGE_GROUP)) +
  geom_line(size = 1, alpha = 0.7) +
  geom_point(size = 3, alpha = 0.7) +
  labs(title = "Total count of crimes against the person of each age group per year",
       x = "Year",
       y = "Total Number of Crimes") +
  scale_y_continuous(breaks = seq(0, max(age_counts$COUNT_), by = 2000)) +
  scale_color_manual(values = c("Youth" = "blue", "Child" = "red", "Adult" = "green", "Unknown" = "purple"),
                     labels = c("Youth" = "Youth", "Child" = "Child", "Adult" = "Adult", "Unknown" = "Unknown")) +  # Specify colors and labels
  theme_minimal()


```
```{r}
#| label: Table-2

library("tidyverse")

# Read data
crime_data <- read_csv("output/data/edited_data.csv",show_col_types = FALSE) 
column_specifications <- spec(crime_data)

# Create a table with unique combinations of AGE_GROUP and corresponding AGE_COHORT values
result_table <- crime_data %>%
  distinct(AGE_GROUP, AGE_COHORT)

# Print the resulting table
print(result_table)
```




